### ISSUE TITLE
Cronjobs

### ISSUE THREAD

**Issue by CokkocZateki** [Shegox/Warcontact_Mangement_System#2]
Hi.

Got an issue with the cronjobs. I keep getting errors.  Any way to work around it.

**Comment by k0478git** [comment]
Could be helpful to give some details on the errors :)

**Comment by CokkocZateki** [comment]
oh wow. u right. 
```
PHP Warning: mysqli::_contruct (): (HY000/2002): Failed to create Unix socket in /var/www/Warcontact_Mangement_System/php/sql.php on line 29

couldn't fetch mysqli in /var/www/Warcontact_Mangement_System/php/www.php on line 22 and 23
```

**Comment by k0478git** [comment]
Looks like you haven't set up your MySql DB , the credentials or the mysqli driver in php.

**Comment by CokkocZateki** [comment]
i have done that on https://github.com/Shegox/Warcontact_Mangement_System/blob/master/php/example.constants.php

imported the .sql into my mysql database and still get this error :(

**Comment by k0478git** [comment]
Why is there a www.php ? That file doesn't exist in the project
Did you rename the sample.constanta  to co

**Comment by k0478git** [comment]
...

Did you rename the sample.constants.php to constants.php?

**Comment by CokkocZateki** [comment]
thats actually a good question about the /www

constant.php has been changed

i think i sorted that out. 
now i get this message in my logs

```
PHP Notice:  Undefined index: state in /var/www/Warcontact_Mangement_System/public/php/addChar.php on line 6
PHP Notice:  Undefined index: state in /var/www/Warcontact_Mangement_System/public/php/addChar.php on line 20
PHP Notice:  Undefined offset: 0 in /var/www/Warcontact_Mangement_System/php/isAuth.php on line 17
PHP Notice:  Undefined index: auth in /var/www/Warcontact_Mangement_System/public/php/getMyChars.php on line 5
PHP Notice:  Undefined index: auth in /var/www/Warcontact_Mangement_System/public/php/getWars.php on line 6
PHP Fatal error:  Uncaught Error: Call to a member function fetch_array() on boolean in /var/www/Warcontact_Mangement_System/php/sql.php:11\nStack trace:\n#0 /var/www/Warcontact_Mangement_System/public/php/getWars.php(9): sql_read('SELECT COUNT(DI...')\n#1 {main}\n  thrown in /var/www/Warcontact_Mangement_System/php/sql.php on line 11
```

**Comment by Shegox** [comment]
It could be the case that the sql.php fetch_array function acts up, could you try to replace it with the block over it:https://github.com/Shegox/Warcontact_Mangement_System/blob/master/php/sql.php

function sql_read($sql)
{
    $conn = connect();
    $result = $conn->query($sql);
    $result = $result->fetch_all(MYSQLI_BOTH);
    $conn->close();
    return $result;
}

**Comment by CokkocZateki** [comment]
ok let me try that option

**Comment by CokkocZateki** [comment]
still the same :(

**Comment by k0478git** [comment]
the errors, as well as their lines, refer to session and global variables. looks to me like you messed up your php configuration and there is no session data. Maybe you disabled php session cookies or something? Can you switch your php.ini to the default production one for testing?

**Comment by CokkocZateki** [comment]
i can certainly give it a try. will need to google it since ive never done it before

**Comment by CokkocZateki** [comment]
```
session.use_only_cookies = 1

session.use_strict_mode = 0

; Whether to use cookies.
; http://php.net/session.use-cookies
session.use_cookies = 1
```

**Comment by CokkocZateki** [comment]
still no luck :(

**Comment by CokkocZateki** [comment]
the struggle is real. still not possible to fix this

**Comment by k0478git** [comment]
I just tried it on a blank installation and can reproduce that error, when I fuckup my mysql connection, like changing user/password/DB-name in the constants.php.
please make sure you've set up the correct connection details and  that you can connect to the DB with these details.
